name: Package Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          zip -r zfgffb_${GITHUB_REF_NAME}.zip . \
            --exclude ".git/*" \
            --exclude ".github/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: zfgffb_${GITHUB_REF_NAME}.zip